# Generated by Django 3.0.2 on 2020-01-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('Length', models.CharField(max_length=2)),
                ('Width', models.CharField(max_length=10)),
                ('HIN', models.CharField(max_length=20)),
                ('Current_Hours', models.CharField(max_length=10)),
                ('Service_Interval', models.CharField(max_length=10)),
                ('Next_Service', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('Seats', models.CharField(max_length=2)),
                ('Color', models.CharField(max_length=10)),
                ('VIN', models.CharField(max_length=20)),
                ('Current_Mileage', models.CharField(max_length=10)),
                ('Service_Interval', models.CharField(max_length=10)),
                ('Next_Service', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('Seats', models.CharField(max_length=2)),
                ('Color', models.CharField(max_length=10)),
                ('VIN', models.CharField(max_length=20)),
                ('Current_Mileage', models.CharField(max_length=10)),
                ('Service_Interval', models.CharField(max_length=10)),
                ('Next_Service', models.CharField(max_length=10)),
                ('Bed_Length', models.CharField(max_length=10)),
            ],
        ),
    ]
