# Generated by Django 3.0.2 on 2020-01-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boat',
            new_name='boats',
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='cars',
        ),
        migrations.RenameModel(
            old_name='Truck',
            new_name='trucks',
        ),
    ]
